name: Hand over tranlation files

on:
  push:
    branches:
      - master
    paths:
      - 'messages/**'
      - '!messages/GE.json'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set current date as env variable
      run: echo "today=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

    - name: Create folder
      run: |
        mkdir -p messages/translated-content && cp messages/GE_* messages/translated-content/
        ls messages/translated-content

    - name: Create pull request to handover translations
      uses: paygoc6/action-pull-request-another-repo@v1.0.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'messages/translated-content/**'
        destination_repo: 'thewahome/react-basics'
        destination_folder: 'src/messages'
        destination_base_branch: 'master'
        destination_head_branch: task/handover-translations-${{ env.today }}
        user_email: ${{ secrets.ACTION_EMAIL }}
        user_name: ${{ secrets.ACTION_USERNAME }}